version: 0.2
phases: 
  install: 
    runtime-versions: 
        php: 7.3 
build: 
  commands:
      - php --version 
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete . "s3://<your-static-website-bucket>"
 post_build:
   commands:
     - echo "post_build step"
