version: 0.2
phases:  
 install: 
  runtime-versions: 
        php: 7.3 
  build: 
    commands: 
      - php --version      
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete . "s3:::codepipeline-eu-west-2-922126377523"
 post_build:
   commands:
     - echo "post_build step"
